version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beathub_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongodb://db:27017/beathub_dev
      JWT_SECRET: your_dev_jwt_secret
      PORT: 3001
    depends_on:
      - db
    volumes:
      - ./src:/home/appuser/app/src

  db:
    image: mongo:6
    container_name: beathub_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpassword
volumes:
  db-data:

